# Generated by Django 3.0.2 on 2020-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('R', 'ROMANCE'), ('A', 'ACTION'), ('D', 'DRAMA'), ('C', 'COMEDY')], max_length=10)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMAN')], max_length=10)),
                ('status', models.CharField(choices=[('MW', 'MOST WATCHED'), ('TR', 'TOP RATED'), ('RA', 'RECENTLY ADDED')], max_length=20)),
                ('year_of_production', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
