# Generated by Django 3.0.2 on 2020-02-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200202_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'ACTION'), ('D', 'DRAMA'), ('R', 'ROMANCE'), ('C', 'COMEDY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='type',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=20),
        ),
    ]
