# Generated by Django 3.0.2 on 2020-02-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200202_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('W', 'WATCH LINK'), ('D', 'DOWNLOAD LINK')], max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'ACTION'), ('C', 'COMEDY'), ('D', 'DRAMA'), ('R', 'ROMANCE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMAN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=20),
        ),
        migrations.DeleteModel(
            name='MovieLinks',
        ),
        migrations.AddField(
            model_name='movielink',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_link', to='movie.Movie'),
        ),
    ]
