# Generated by Django 3.0.2 on 2020-02-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200202_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('C', 'COMEDY'), ('R', 'ROMANCE'), ('D', 'DRAMA'), ('A', 'ACTION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('GR', 'GERMAN'), ('EN', 'ENGLISH')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('MW', 'MOST WATCHED'), ('RA', 'RECENTLY ADDED'), ('TR', 'TOP RATED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='type',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=20),
        ),
    ]
