# Generated by Django 3.0.2 on 2020-02-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200202_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'ACTION'), ('R', 'ROMANCE'), ('C', 'COMEDY'), ('D', 'DRAMA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('TR', 'TOP RATED'), ('MW', 'MOST WATCHED')], max_length=20),
        ),
    ]
